FROM ubuntu:20.04
RUN apt update && apt upgrade
WORKDIR /vacancy_analyzer
COPY entrypoint.sh ./
RUN chmod a+x entrypoint.sh
RUN pip install -r requirements.txt
ENTRYPOINT [ "./entrypoint.sh" ]
CMD [ "ls" ]