FROM ubuntu:20.04
RUN apt update && apt upgrade
WORKDIR /vacancy_analyzer
COPY entrypoint.sh ./
RUN chmod a+x entrypoint.sh
COPY requirements.txt /tmp/
RUN apt install -y python3-pip
RUN apt install python3.8
RUN pip install -r /tmp/requirements.txt
COPY . /tmp/
ENTRYPOINT [ "./entrypoint.sh" ]
CMD [ "ls" ]